### ISSUE TITLE
Plugin configs - doesn't saved and are reset after each update (v3.0.1)

### ISSUE THREAD

**Issue by Bonbeart** [appodeal/appodeal-unity-plugin-upm#6]
## Step 1: Environment

 - Computer OS: Windows 10
 - Unity Editor Version: 2020.3.38f1
 - Appodeal Unity Plugin Version: 3.0.1
 - Bug Repro Rate: 100%

## Step 2: Describe the bug
I don't use 3rd party libraries and delete them via Appodeal SDK Manager, but these configs are reset after each update.
And I have to carefully go through the changes in VCS - to prevent this.

## Step 3: How to reproduce
Update Appodeal plugin via UPM

## Step 4: Expected behavior
The configs remain the same

## Step 5: Screenshots
Screenshot from previous version of Appodeal SDK Manager.
I can't show actual version of window itself because of this issue: #4 
![image](https://user-images.githubusercontent.com/39597999/199882844-963c0118-4297-4518-974a-11a342521440.png)

![image](https://user-images.githubusercontent.com/39597999/199878666-f898b630-e8c1-4c10-a847-aff2ff63676e.png)

## Step 6: Additional context
If any changes are made to the dependencies in the files themselves (e.g. when git merging, or manually editing them) and Unity is open in the background, then the dependencies revert back to the state specified in the Unity plugin window. Although it should be the files themselves, as the primary sources, that have priority.

**Comment by DmitriiFeshchenko** [comment]
Hi, @Bonbeart!

As you can get from #4, the version you use is not a release. Therefore it may change. The issue you describe was fixed here: [link](https://github.com/appodeal/appodeal-unity-plugin-upm/commit/3e03a1875c0ec0bd3249daccd15c101c221221c8), [link](https://github.com/appodeal/appodeal-unity-plugin-upm/commit/dec8a6e31b7c3b530322f7acb1611b483301aafb). However, we don't know when you installed the plugin and whether or not the fixes were applied there.

Could you please try to update v3.0.1 to the current state and check if the issue is resolved? If it is not, let me know how to reproduce the bug step by step.

I'm waiting for your answer.

Best Regards,

**Comment by Bonbeart** [comment]
Hello, I installed and updated the plugin today, the error exists at the moment and it is not fixed.

**Comment by DmitriiFeshchenko** [comment]
@Bonbeart, could you please let me know how to reproduce the bug step by step? Unfortunately, it's not so clear from your initial message.

**Comment by Bonbeart** [comment]
Yes, of course.

My Steps:

1. Open Unity

2. I have installed version 3.0.1 of this [revision](https://github.com/appodeal/appodeal-unity-plugin-upm/commit/2a007da6a084afa98526e25d9dcdd58275264321). Unnecessary dependencies were disabled, dependencies files have an empty <dependencies> block

3. Update Appodeal SDK to the latest [revision](https://github.com/appodeal/appodeal-unity-plugin-upm/commit/d289e90dfbe5aa181037a4fef25783a2931277b5) of 3.0.1

4. According to the changes in VCS, we see that dependencies has been returned to the <dependencies> block, this should not have happened

-----
Disable dependencies: Adjust, AppsFlyer, Firebase, Meta, StackAnalytics.

**Comment by DmitriiFeshchenko** [comment]
@Bonbeart, what do you mean by this?

> Update Appodeal SDK to the latest [revision](https://github.com/appodeal/appodeal-unity-plugin-upm/commit/d289e90dfbe5aa181037a4fef25783a2931277b5) of 3.0.1

Did you uninstall the plugin via _Appodeal -> Remove plugin_ tool and then install the new version?

> According to the changes in VCS, we see that dependencies has been returned to the block, this should not have happened

According to the current Implementation, all dependencies are synced with the default ones at the plugin installation.

Please, describe the exact steps I can follow to reproduce your use case to see whether or not it is a bug.

**Comment by Bonbeart** [comment]
I'm sorry, but I also have work to do and I value my time.

I described the specific steps in a previous post. I did not uninstall Appodeal (I already had Appodeal 3.0.1 installed and I updated to the latest revision of the same version, which I detailed in a previous post)



> According to the current Implementation, all dependencies are synced with the default ones at the plugin installation.

Default? 

That's what I'm talking about - that you don't need a default reset... why? 
I adjust the plugin for me, and you reset these settings, after each update.

Please read my first post, so I also tried to describe this problem in detail.

**Comment by DmitriiFeshchenko** [comment]
Your Unity Editor version doesn't support updating packages installed from GitHub. The second option, which is using SDK Manager, is also not available for obvious reasons. Thus, it's not clear to me what you mean by:

> Update Appodeal SDK to the latest [revision](https://github.com/appodeal/appodeal-unity-plugin-upm/commit/d289e90dfbe5aa181037a4fef25783a2931277b5) of 3.0.1

And that is why I asked to describe the exact steps, as I was not able to reproduce this behavior myself.

Dependencies are a part of a plugin and are being updated altogether with the rest of the content.

There are two ways this can be managed. It's either not having any dependencies installed by default or updating all of them. As there are cases where some old dependencies are removed, or new ones are added, we cannot leave them unchanged.

At the moment, the reworked version of SDK Manager is in development. I will add a note to study your case, but not sure if there is a better solution.

For now, the only way is to discard the unwanted changes when pushing a commit.

**Comment by Bonbeart** [comment]
What the hell are you talking about?!

My version doesn't support UPM - are you serious?!
![image](https://user-images.githubusercontent.com/39597999/200063763-bf714932-4e8c-4962-94c6-67ba57ba8fed.png)


Please take care of the problem instead of looking for excuses. 

Overall, I now understand why your product is of such shitty quality...

**Comment by Bonbeart** [comment]
If you do not understand my steps - then show them to your senior programmer, I have described everything to you in detail.

**Comment by DmitriiFeshchenko** [comment]
@Bonbeart, let me try to explain this one more time.

> your Unity Editor version doesn't support **UPDATING** packages installed from GitHub.

 It's the button called "Update" which is placed next to the "Remove" button. It was added in the 2021 version of Unity.

Unless you provide us with sufficient information to reproduce the issue, I'm not able to help you.

**Comment by Bonbeart** [comment]
@DmitriiFeshchenko, Oh my God... why do you need the refresh button?!

Open a dependency file, save it - Unity picks up the changes and loads the last available commit on the specified branch.

Should I send you the actual code if you still don't believe me?!

**Comment by Bonbeart** [comment]
@DmitriiFeshchenko,

My Steps:

0. Enable Your PC (**seriously, without that, nothing will work**.)

0. Login to windows (password entry may be required, but it's not complicated)

0. Wait before windows is started completely (okay, that's a relief.)

1. Open Unity (any version with support UPM)

2. Install SDK version by this commit [revision](https://github.com/appodeal/appodeal-unity-plugin-upm/commit/2a007da6a084afa98526e25d9dcdd58275264321).

    Let me explain in more detail how to do it 
    - Open the file with the packages of unity (should I specify where it is located?)
    - Specify a reference to a particular commit (by its hash), it is done as follows:
`"com.appodeal.appodeal-unity-plugin-upm": "https://github.com/appodeal/appodeal-unity-plugin-upm.git#2a007da6a084afa98526e25d9dcdd58275264321",`

5. Disable Unnecessary dependencies 
(dependencies files have an empty block on this moment).
    

6. Update Appodeal SDK to the latest [revision](https://github.com/appodeal/appodeal-unity-plugin-upm/commit/d289e90dfbe5aa181037a4fef25783a2931277b5) of 3.0.1

    Let me explain in more detail how to do it:
    - Open the file with the packages of unity (should I specify where it is located?)
    - Specify a reference to a target branch:
`"com.appodeal.appodeal-unity-plugin-upm": "https://github.com/appodeal/appodeal-unity-plugin-upm.git#feature/release-3.0.1",`


4. According to the changes in VCS, we see that dependencies has been returned to the block `<dependencies>`, this should not have happened

**Comment by Bonbeart** [comment]
🤦‍♂️ I just don't understand why I have to describe such an elementary operation.

Just take any previous version from upm (change dependencies, ie. remove some) and upgrade to the next version - the dependencies (Appodeal SDK Manager) will be reset.

**Comment by DmitriiFeshchenko** [comment]
@Bonbeart, hi!

I did check this behavior on a Windows PC. Unfortunately, I wasn't able to reproduce the issue. [Here](https://github.com/DmitriiFeshchenko/bonbeart-apd-bug/commits/main) is the repo I used.

Please, provide me with a sample project, or let me know if some required steps were missing.

Best Regards,

**Comment by DmitriiFeshchenko** [comment]
I'm closing this issue for now, as there are no updates.

**Comment by Bonbeart** [comment]
@DmitriiFeshchenko I'm sorry, I missed the notification.

Maybe in a previous update, there was some data cached or something like that, but I restarted Unity and checked twice, the problem persists.

Now I repeated these steps and everything is OK. The configuration is saved during the update.
